# Generated by Django 4.2.5 on 2023-09-14 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('releaseDate', models.DateField()),
                ('description', models.TextField()),
                ('img', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_condtion', to='retroapi.condition')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_collection', to='retroapi.console')),
            ],
        ),
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('releaseDate', models.DateField()),
                ('description', models.TextField()),
                ('img', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControllerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_condition', to='retroapi.condition')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_collection', to='retroapi.controller')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('releaseDate', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('modes', models.CharField(max_length=255)),
                ('img', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_condition', to='retroapi.condition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_collection', to='retroapi.game')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consoles', models.ManyToManyField(through='retroapi.ConsoleCollection', to='retroapi.console')),
                ('controllers', models.ManyToManyField(through='retroapi.ControllerCollection', to='retroapi.controller')),
                ('games', models.ManyToManyField(through='retroapi.GameCollection', to='retroapi.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gamecollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_game', to='retroapi.owner'),
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_genre', to='retroapi.genre'),
        ),
        migrations.AddField(
            model_name='controllercollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_controller', to='retroapi.owner'),
        ),
        migrations.AddField(
            model_name='consolecollection',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_console', to='retroapi.owner'),
        ),
    ]
