# Generated by Django 4.2.5 on 2023-09-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retroapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
