# Generated by Django 4.2.5 on 2023-09-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retroapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='consoles',
            field=models.ManyToManyField(related_name='owners', to='retroapi.console'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='controllers',
            field=models.ManyToManyField(related_name='owners', to='retroapi.controller'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='games',
            field=models.ManyToManyField(related_name='owners', to='retroapi.game'),
        ),
    ]
