# Generated by Django 4.2.5 on 2023-09-13 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retroapi', '0002_alter_owner_consoles_alter_owner_controllers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='console_condition', to='retroapi.condition'),
        ),
        migrations.AlterField(
            model_name='controller',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_condition', to='retroapi.condition'),
        ),
        migrations.AlterField(
            model_name='game',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_condition', to='retroapi.condition'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GameCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.condition')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.game')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_game', to='retroapi.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ControllerCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.condition')),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.controller')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_controller', to='retroapi.owner')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.condition')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retroapi.console')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_console', to='retroapi.owner')),
            ],
        ),
        migrations.AlterField(
            model_name='owner',
            name='consoles',
            field=models.ManyToManyField(through='retroapi.ConsoleCollection', to='retroapi.console'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='controllers',
            field=models.ManyToManyField(through='retroapi.ControllerCollection', to='retroapi.controller'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='games',
            field=models.ManyToManyField(through='retroapi.GameCollection', to='retroapi.game'),
        ),
    ]
